# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Croix Hollow"
email: "hello@croixhollow.com"
description: >-
  A luxury cedar home nestled on 12 acres of the St. Croix River Valley in Scandia, Minnesota.
  The perfect setting for your weekend away, family get-together, or romantic escape, just 45 minutes from Minneapolis.
image: "/assets/images/share.jpg"
logo: "/assets/images/logo_white.png"
baseurl: ""
url: "https://croixhollow.com/"

airbnb_url: https://www.airbnb.com/rooms/50934412
vrbo_url: https://www.vrbo.com/2675571

instagram: CroixHollow
facebook: CroixHollow
twitter: CroixHollow

google_measurement_id: G-ZRQ8JGEKDX

markdown: kramdown

sass:
  sass_dir: assets/css

plugins:
  - jekyll-redirect-from

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

