# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Croix Hollow"
email: "hello@croixhollow.com"
description: >-
  A scandinavian cedar home is nestled on 12 acres in the St. Croix River Valley.
  Featuring a soaring great room, updated kitchen,
  3 gas fireplaces, 4 bedrooms, 3 bathrooms, sauna, bar, & theater!
image: ""
baseurl: ""
url: "https://croixhollow.com/"

markdown: kramdown

sass:
  sass_dir: assets/css

plugins:
  - jekyll-redirect-from

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

